name: "run with self hosted runners"

on:
  push:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  run_libp2p_interop_on_local_self_hosted_docker:
    uses: ./.github/workflows/custom-run-interop.yml
    with:
      # testground_endpoint: local
      testground_runner: local:docker
      collect_name: run_libp2p_interop_on_local_docker
  run_libp2p_ping_on_local_self_hosted_docker:
    uses: ./.github/workflows/custom-run-ping.yml
    with:
      # testground_endpoint: local
      testground_runner: local:docker
      collect_name: run_libp2p_ping_on_local_docker
  run_examples_pingpong_on_local_self_hosted_docker:
    uses: ./.github/workflows/custom-run-ping-pong.yml
    with:
      # testground_endpoint: local
      testground_runner: local:docker
      collect_name: run_examples_pingpong_on_local_docker
  run_sdk_rust_on_local_self_hosted_docker:
    uses: ./.github/workflows/custom-run-rust.yml
    with:
      # testground_endpoint: local
      testground_runner: local:docker
      collect_name: run_sdk_rust_on_local_docker