on:
  workflow_dispatch:
    inputs:
      testground_endpoint:
        type: string
        required: false
        description: testground endpoint
      custom_git_reference:
        type: string
        required: false
        description: go ref
name: Testground Demo Go Interop Tests

jobs:
  run-libp2p-test-plans:
    uses: "singulargarden/test-plans/.github/workflows/run-composition.yml@master"
    with:
      composition_file: "ping/_compositions/go-cross-versions.toml"
      custom_git_reference: ${{ github.event.inputs.custom_git_reference }}
      testground_endpoint: ${{ github.event.inputs.testground_endpoint }}