on: [push, pull_request]
name: Test refs!
# echo all ${{ github.event.pull_request }}
# echo "${{ toJSON(github.event.pull_request) }}"

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: show the refs
        shell: bash
        run: |
          echo the commit I care about is: ${{ github.event.pull_request.head.sha || github.sha }}
          echo github.sha: ${{ github.sha }}
          echo github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}
          echo github.event.pull_request.head.repo.name: ${{ github.event.pull_request.head.repo.name }}


# # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# # https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request
# echo the branch I care about is: ${{ github.head_ref || github.ref_name }}
# # The head_ref or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.
# echo github.head_ref ${{ github.head_ref }}
# # The base_ref or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.
# echo github.base_ref ${{ github.base_ref }}
# echo github.ref ${{ github.ref }}
# echo github.ref_name ${{ github.ref_name }}
# echo github.sha ${{ github.sha }}
# echo github.repository ${{ github.repository }}
# echo github.event.pull_request.head.ref ${{ github.event.pull_request.head.ref }}
# echo github.event.pull_request.repo.git_url ${{ github.event.pull_request.head.repo.git_url }}
# echo url == github.com/${{ github.event.pull_request.head.repo.full_name }}@${{ github.event.pull_request.head.sha }} 
# echo github.event.pull_request.merge_commit_sha ${{ github.event.pull_request.merge_commit_sha }}
# git clone https://github.com/${{ github.repository }} my-repo
# cd my-repo
# git fetch --all
# git show ${{ github.sha }}