on: [push, pull_request]
name: Test refs!

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: show the refs
        shell: bash
        run: |
          echo github.head_ref || github.ref ${{ github.head_ref || github.ref }}
          echo github.head_ref ${{ github.head_ref }}
          echo github.ref ${{ github.ref }}