on:
  workflow_dispatch:
name: Testground Interop Tests

jobs:
  test-interop:
    uses: laurentsenta/test-plans/.github/workflows/test-compatibility.yml@compatibility-and-reusable
    with:
      testplan: "c"
      testcase: "x"
      rust-ref: "a"
      go-ref: "e8a2c74b83aee579d52179d4ffb5e94b1d207a77"